- .pre-commit-config.yaml
Added configuration for pre-commit.ci app
> Added pre-commit-ci configuration

- README.md
- pdm.lock
- pyproject.toml
> Add bumpver for versioning

- .pre-commit-config.yaml
- docs/about.md
> feat: added typos pre-commit hook

- .github/workflows/_tests.yml
- .github/workflows/full-ci.yml
- .github/workflows/run-tests.yml
- .github/workflows/spell-check.yml
- .pre-commit-config.yaml
- .vscode/extensions.json
- cspell.config.yaml
Replaced old library with new cspell and added extension recommendation
> feat: replace code-spelling-check

- .github/workflows/full-ci.yml
- mkdocs.yml
- pdm.lock
- pyproject.toml
- Added `mike` dependency
- Configured automatic `dev` documentation deploy for all new commits into `main` branch
- Configured automatic documentation version update using bumpver release tag with `latest` relabeling
> docs: added mike dependency and automatic deploy

- pdm.lock
- pyproject.toml
> chore: removed pydantic dependency

- .github/workflows/full-ci.yml
Repaired bug where the main package wasn't installed and example notebooks weren't executed properly.
> ci: fix mike build

- CHANGELOG.md
- examples/joiners/README.md
- examples/joiners/intersection_joiner.ipynb
- srai/joiners/__init__.py
- srai/joiners/base.py
- srai/joiners/intersection_joiner.py
- tests/joiners/conftest.py
- tests/joiners/test_intersection_joiner.py
> feat: add IntersectionJoiner

- CHANGELOG.md
- pyproject.toml
> build: deploy srai 0.0.1

- srai/joiners/base.py
- srai/joiners/intersection_joiner.py
- tests/joiners/test_intersection_joiner.py
> feat: add option to return result without geometry in Joiners

- srai/joiners/base.py
- srai/joiners/intersection_joiner.py
> fix: remove duplicated code from joiners

- .github/workflows/ci-dev.yml
- .github/workflows/ci-prod.yml
- mkdocs.yml
Closes #116 
Closes #118 
Resigned from Overpass cache for mkdocs deployment, because of temporal directories usage by mkdocs-gen-files plugin.
> Check overpass cache for docs deployment

- examples/regionizers/s2_regionizer.ipynb
- pdm.lock
- pyproject.toml
- srai/regionizers/__init__.py
- srai/regionizers/s2_regionizer.py
- tests/regionizers/test_s2_regionizer.py
> feat: add S2Regionizer

- examples/regionizers/README.md
> docs: add S2Regionizer example reference in docs

- examples/regionizers/h3_regionizer.ipynb
- examples/regionizers/s2_regionizer.ipynb
> fix: extract H3 and S2 resolution to more exposed spot in example notebooks

- README.md
- Modified URLs of badges
- Split dev and prod deployments
> chore: applied changes required by shields.io

- CHANGELOG.md
- examples/embedders/count_embedder.ipynb
- examples/joiners/intersection_joiner.ipynb
- srai/embedders/base.py
- srai/embedders/count_embedder.py
- srai/joiners/base.py
- srai/joiners/intersection_joiner.py
- tests/embedders/test_count_embedder.py
- tests/joiners/test_intersection_joiner.py
> chore: update Joiners and Embedders to have transform method

- srai/loaders/geoparquet_loader.py
- srai/regionizers/administrative_boundary_regionizer.py
- srai/regionizers/base.py
- srai/regionizers/h3_regionizer.py
- srai/regionizers/s2_regionizer.py
- srai/regionizers/voronoi_regionizer.py
- srai/utils/constants.py
> chore: extract shared code between regionizers

- .github/workflows/ci-dev.yml
- .github/workflows/ci-prod.yml
> fix: pass python version as str to avoid wrong parsing

- examples/regionizers/voronoi_regionizer.ipynb
- srai/regionizers/_spherical_voronoi.py
- srai/regionizers/voronoi_regionizer.py
- tests/regionizers/test_voronoi_regionizer.py
> feat: add option to specify number of cpu threads

- srai/embedders/__init__.py
- srai/embedders/_base.py
- srai/embedders/count_embedder.py
- srai/embedders/gtfs2vec_embedder.py
- srai/joiners/__init__.py
- srai/joiners/_base.py
- srai/loaders/__init__.py
- srai/loaders/_base.py
- srai/regionizers/__init__.py
- srai/regionizers/_base.py
- srai/regionizers/administrative_boundary_regionizer.py
- srai/regionizers/h3_regionizer.py
- srai/regionizers/s2_regionizer.py
- srai/regionizers/voronoi_regionizer.py
`_base` files are inspired by scikit-learn modules structure.
> chore: modify base classes names

- CHANGELOG.md
- examples/embedders/highway2vec_embedder.ipynb
- examples/loaders/osm_way_loader.ipynb
- srai/constants.py
- srai/embedders/__init__.py
- srai/embedders/_base.py
- srai/embedders/highway2vec/__init__.py
- srai/embedders/highway2vec/embedder.py
- srai/embedders/highway2vec/model.py
- srai/joiners/intersection_joiner.py
- srai/loaders/osm_way_loader/constants.py
- srai/loaders/osm_way_loader/osm_way_loader.py
- tests/embedders/test_highway2vec_embedder.py
- tests/joiners/conftest.py
- tests/joiners/test_intersection_joiner.py
- tests/loaders/osm_way_loader/test_osm_way_loader.py
> feat: add Highway2Vec

- .github/workflows/run-changelog-enforcer.yml
- CHANGELOG.md
> ci: Changelog enforcer

- CHANGELOG.md
- CITATION.cff
> feat: add citation info

- .github/workflows/ci-dev.yml
- .github/workflows/ci-prod.yml
- CHANGELOG.md
- docs/.pages
- docs/README.md
- docs/examples/README.md
- docs/gen_ref_pages.py
- docs/generate_api.py
- docs/getting_started/README.md
- docs/getting_started/use_cases.md
- mkdocs.yml
- srai/embedders/__init__.py
- srai/joiners/__init__.py
- srai/loaders/__init__.py
- srai/neighbourhoods/__init__.py
- srai/plotting/__init__.py
- srai/regionizers/__init__.py
- srai/regionizers/voronoi_regionizer.py
- srai/utils/__init__.py
> docs: create initial documentation 

- .pre-commit-config.yaml
- CHANGELOG.md
- pdm.lock
- pyproject.toml
- srai/loaders/osm_loaders/pbf_file_downloader.py
- tests/embedders/test_contextual_count_embedder.py
- tests/embedders/test_count_embedder.py
> chore: make srai compatible with pandas 2.0

- .pre-commit-config.yaml
- CHANGELOG.md
- examples/embedders/highway2vec_embedder.ipynb
- examples/embedders/load_and_save.ipynb
- srai/embedders/__init__.py
- srai/embedders/_base.py
- srai/embedders/count_embedder.py
- srai/embedders/gtfs2vec/embedder.py
- srai/embedders/gtfs2vec/model.py
- srai/embedders/hex2vec/embedder.py
- srai/embedders/hex2vec/model.py
- srai/embedders/highway2vec/embedder.py
- srai/embedders/highway2vec/model.py
> feat: add loading and saving fittable Embedders

- README.md
> feat: add info about pre-trained models to README

- CHANGELOG.md
- pdm.lock
- pyproject.toml
> fix: freeze osmnx version to 1.4.0 to remove incompatibility issue with 1.5.0

- .github/workflows/_tests.yml
- .github/workflows/release.yml
- CHANGELOG.md
- pyproject.toml
- srai/loaders/osm_loaders/pbf_file_downloader.py
Removed validation of simplified polygon and sped up buffering process.
> fix: polygon validation results in geometrycollection object has no attribute exterior

- CHANGELOG.md
- pdm.lock
- pyproject.toml
- srai/embedders/hex2vec/embedder.py
- srai/regionalizers/h3_regionalizer.py
- tests/embedders/hex2vec/generation.py
> refactor: Increase H3Regionalizer transform speed

- CHANGELOG.md
- CITATION.cff
- pyproject.toml
- srai/__init__.py
> feat: expand version bumping with bumpver

- README.md
- docs/getting_started/README.md
> docs: info about tutorial

- CITATION.cff
Add reference to the GeoAI publication
> chore: update CITATION.cff
